runtime: ruby
env: flex
entrypoint: bundle exec rackup --port $PORT

handlers:
  - url: /
    http_headers:
      Access-Control-Allow-Origin: *

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10